### ISSUE TITLE
SQL scripts have invalid SQL syntax with PostgreSQL

### ISSUE THREAD

**Issue by sandor-szendro-i4p** [Keyfactor/ejbca-ce#26]
sql-scripts/create-index-ejbca.sql has the following error with PostgreSQL (tested with 13):

STATEMENT:  DROP INDEX IF EXISTS crldata_idx3 ON CRLData;
db_1     | ERROR:  syntax error at or near "ON"
db_1     | LINE 1: DROP INDEX IF EXISTS crldata_idx3 ON CRLData;

The "ON CRLData"  should be removed for these 2 entries:
DROP INDEX IF EXISTS crldata_idx3 ON CRLData;
DROP INDEX IF EXISTS crldata_idx4 ON CRLData;

**Comment by primetomas** [comment]
It seems DROP INDEX sql syntax differs too much between databases to be general. All create index syntax works on all(?) databases, but clearly not drop index. 
Since the drop index lines are needed only for certain updates, for a specific version when CRL partitions were introduced, one way of doing it would be to simply comment out those lines and require users to manually run them when upgrading.

**Comment by primetomas** [comment]
Thanks for the report. We fixed it by commenting out the drop index lines (for the next feature release), since it's only needed for specific upgrades and can be run manually in those cases.
https://jira.primekey.se/browse/ECA-10601
