### ISSUE TITLE
EJBCA 8.0 sample index does not work with PostgreSQL

### ISSUE THREAD

**Issue by simplysoft** [Keyfactor/ejbca-ce#317]
The newly introduced index  in commit 590e8b5a4a96778e60c091b5ccd0f9445fe8f56e does not work with PostgreSQL (version 15)
https://github.com/Keyfactor/ejbca-ce/blob/ce7f5e74b9a054edf61b188fa46f03e57b8478ab/doc/sql-scripts/create-index-ejbca.sql#L63

Error:
```
ERROR: function subjectaltname(integer) does not exist
```

**Comment by primetomas** [comment]
The comments around this index should explain it.

-- The subjectAltName index could be configured either to match only the first 750 characters, or to match the full row, using a slower full-text index.
CREATE INDEX certificatedata_idx_san ON CertificateData (subjectAltName(750));
-- or, for slower full-text querying: CREATE FULLTEXT INDEX certificatedata_idx_san ON CertificateData (subjectAltName);

Is it possible on postgres to create a limited index like this? Otherwise just replace it with the fulltext index.

**Comment by primetomas** [comment]
see #336 for a solution. OIther than using a full text index, which is also a workable way when your database is not very large. 
Added to the sql script as a comment for the next release. 

Thanks for the report.
