### ISSUE TITLE
Notification contains no password after editing an entity in RA UI Version 7.11.0 Community

### ISSUE THREAD

**Issue by floriankoenig-work** [Keyfactor/ejbca-ce#441]
I have an EndEntityProfile which should email the enrollment code/password to the user. 
(Sent on event STATUSNEW, Message contains ${user.USERNAME} and ${user.PASSWORD})

Via adminweb, this works after initial creation of an user end enitity and after editing if "Regenerate new Pasword" was selected.

Via RA UI only the notification after creation contains the password. After editing the Notification is sent, but contains no password.
Enrollment code "Autogenerated password" has been checked.

**Comment by floriankoenig-work** [comment]
Any news on this?

**Comment by primetomas** [comment]
I got around to testing this now, using the latest version of the Container on DockerHub (8.2.0.1).

1. I create an End entity in Admin UI, with autogenerated password, and receive an email notification with username and password
2. I open the RA UI and edit the end entity, first I have to set status to Generated, otherwise nothing is edited because the UI thinks I didn't change anything
3. In the RA UI I edit the end entity again setting status to new, the checkbox autogenerated password is checked (by default). I receive an email notification with username and password.

**Comment by floriankoenig-work** [comment]
Ah my bad. I thought is's sufficient to check "autogenerated password".

I can verify the notification works correctly if the entities status is changed to generated and then to new.
