### ISSUE TITLE
I can't access superadmin console

### ISSUE THREAD

**Issue by jhondari1989** [Keyfactor/ejbca-ce#65]
Hello, I have installed the docker version of ejbca, with the Quick Start: Classic Workflow, with the command line
`docker run -it --rm -p 80:8080 -p 443:8443 -h mycahostname keyfactor/ejbca-ce`
I am able to access and download the superadmin.p12 certificate and import it into my browser, however it does not allow me to access the ejbca admin console "https://localhost/ejbca/adminweb/" I get the message "Authorization Denied
No client certificate was presented". Can you help me please?

**Comment by pkmarios** [comment]
Did the browser prompt for a certificate authentication at all? This is probably related to your browser is set to not send a client certificate for 'localhost' per se, or a different certificate is already configured to authenticate with localhost, mostly from a previous run.

On a general note, each new run _(per the given command)_ will generate a fresh superadmin from a fresh CA, using `--rm` will make it ephemeral, so the previous runs' superadmin(s) won't work.

A few possible tracking approaches:

- Try a Private/Incognito Window and select the correct superadmin from the same run, or use a different browser.
- Use the machine hostname instead of 'localhost' or the local network IP, so if 'localhost' is currently bound to another imported certificate, this should make the browser to prompt anew.
- Start over clean:
  1. Stop any ejbca running container
  2. Assuming Firefox → Settings → Privacy & Security → View Certificates → Your Certificates → Under EJBCA Container Quickstart → Remove all previous superadmin(s) - if any
  3. Same dialog → Authentication Decisions tab → select and delete all lines with Host: localhost
  4. Close all tabs and windows
  5. Run a new container and a new browser window → enroll the superadmin p12 → import it to the browser → go to https://localhost/ejbca/adminweb/ → Select the superadmin certificate when prompted
  - P.S. Alternatively, ignore steps 2-3 and create a new Firefox profile.

That said, for testing only you could also omit using client SuperAdmin authentication to start with:
`docker run -it --rm -p 80:8080 -p 443:8443 -h mycahostname -e TLS_SETUP_ENABLED="simple" keyfactor/ejbca-ce`
Then navigate to adminweb and click cancel if/when prompted for a certificate authentication.

**Comment by jhondari1989** [comment]
I have solved it, when selecting the algorithm select RSA 2048 and it worked. Thanks.

**Comment by primetomas** [comment]
Great. Thanks.

**Comment by pkmarios** [comment]
> I have solved it, when selecting the algorithm select RSA 2048 and it worked. Thanks.

Sounds good! Would you mind telling us which key type (and length) you were using previously, i.e. when facing the issue? And which browser/version?

**Comment by jhondari1989** [comment]
> 

Hi, I previously used DSA 1024 in Google Chrome 104.0.5112.102.

**Comment by mike-agrenius-kushner** [comment]
Just as an aside, I'd very highly discourage you from using DSA 😬 We still support it for legacy reasons, but I'd highly recommend that you go with EC P384 or RSA 2048 instead. 

See: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca5384

Cheers,
Mike
