### ISSUE TITLE
Unable to build local documentation

### ISSUE THREAD

**Issue by uedvt359** [Keyfactor/ejbca-ce#80]
**Summary**:
- local documentation cannot be built, and no pre-built version is avaliable for download

**Environment**:
- EJBCA-CE 7.9.0.2
- WildFly 24.0.1.Final
- RHEL 8.6 x86_64

**Details**:

When building EJBCA 7.9.0.2, the internal documentation is not included.  It only says:

>If you're seeing this page then EJBCA has been built directly from GIT without access to PrimeKey's Confluence server.
>
>Build using ant doc -Ddoc.update=true to update.

However, the documentation cannot be built, since it requires API access to keyfactor's confluence server. Here are the relevant lines from the ant output:

```
doc-confluence-from-server:
    [mkdir] Created dir: /opt/ejbca-ce-EJBCA_7_9_0_2_20220616/tmp/htdocs/docs
Unknown host: none

BUILD FAILED
/opt/ejbca-ce-EJBCA_7_9_0_2_20220616/docs.xmli:127: The following error occurred while executing this line:
/opt/ejbca-ce-EJBCA_7_9_0_2_20220616/docs.xmli:142: Could not contact Confluence Server at http://none:-1/. doc.update=true
```

Worse, when clicking the `[?]` buttons next to each settings option (these should link directly to subpages describing the relevant options), these links now return an unhelpful 404, since no documentation is available. it also appears that pre-built documentation is not available for download (at least, not that we could find).

Changing `web.docbaseuri` to point to the online docs is not ideal, because we need access to the documentation during emergencies, and does not work anyways due to a seperate Bug I'll file shortly.

**Comment by primetomas** [comment]
Thanks for the report. 
We'll look at how releases on GitHub can work with the documentation. You can download the zip release from here, which includes the documentation.
https://sourceforge.net/projects/ejbca/files/ejbca7/

And no, you will not be able to download at build as the confluence is not available externally.

I created this issue internally: https://jira.primekey.se/browse/ECA-10906

**Comment by uedvt359** [comment]
Thank you for the quick response. I was unaware that there is a difference between the Github and Sourceforge downloads. https://www.ejbca.org/download/ lists GH first, so we chose to download from there. We copied doc/dist from SF into our installation and it works, so thanks very much!

**Comment by fliegerwolf** [comment]
Hey uedvt359,

> We copied doc/dist from SF into our installation and it works, so thanks very much!

I couldn't find the doc/dist folder/zip file anywhere under https://sourceforge.net/projects/ejbca/ 
Would you reply with the location of this as it seems to be exactly was is missing for us as well.
Thanks!

**Comment by primetomas** [comment]
On the sourceforge page you look under files and download the lastest zip release of EJBCA. Inside that zip file you will find doc/dist (I just verified it)

**Comment by fliegerwolf** [comment]
> On the sourceforge page you look under files and download the lastest zip release of EJBCA. Inside that zip file you will find doc/dist (I just verified it)

Oops! Somehow I missed that in the subfolder...
And apparently its just that kind of day. I was able to compile(?) the docs using `ant doc` and modified the web.properties `web.docbaseuri=file:///etc/ejbca-ce/tmp/htdocs/docs/index.html` restarted wildfly and even tried `ant deployear` but I still can't get context help and the documentation link at bottom of ejbca page still sends me to the "EJBCA - Documentation Placeholder" page with the suggestion to `ant doc -Ddoc.update=true to update.`

What am I missing?
Thanks for the help

**Comment by uedvt359** [comment]
all we did was copy the `/doc/dist` directory from the SF zip to `/etc/ejbca/doc/dist`. you don't need to run `ant doc`, only primekey/keyfactor have access to their confluence api, that is needed for this.

i don't think we modified the `web.properties` config file; the `web.docbaseuri` is commented out and that works for us.

**Comment by fliegerwolf** [comment]
> all we did was copy the `/doc/dist` directory from the SF zip to `/etc/ejbca/doc/dist`. you don't need to run `ant doc`, only primekey/keyfactor have access to their confluence api, that is needed for this.
> 
> i don't think we modified the `web.properties` config file; the `web.docbaseuri` is commented out and that works for us.

Thanks but no, that didn't work either.  I guess I'll use the SF version when I build PRD and hopefully it'll work then.
Oh and how did you do your build? From source, use docker or...? I ended up writing 5 scripts to install everything cuz the online guide left SOOO much out due to alot of assumptions that the authors didn't document so it wasn't a matter of copy and paste and away you go but at least it eventually worked.

**Comment by primetomas** [comment]
What did you find missing from the installation docs? Suggestions for improvement are always welcome. Can you name some assumptions that the authors didn't document?
Always hard when you've done something 1000 times, really appreciate any feedback.

**Comment by fliegerwolf** [comment]
Hi Tomas,

First please don't think I'm purposefully being harsh on your company or
product, it is a great product and has allowed us to have a non-MS PKI
infrastructure for the Financial industry based cyber security team I'm
consulting for. However, it took me over 3 weeks to finally get this
product installed properly and it really boiled down to missing/assumed
information in the documentation and to be fair, my own pitbull-like
stubbornness thinking I could figure it out, which of course I did...
eventually. But I should have reached out to EJBCA sooner, working in IT
for over 20+ years, I guess I had some pride or something to prove, another
lesson learned.

Anyway, while the official documentation is quite extensive and absolutely
necessary in building the environment, it was lacking in completeness and
didn't flow very well at times.  Especially in the main portion, installing
the Application Servers, that section just goes on and on... For example,
from the very top, it says: Using the Zip Package... Download and unpack
the WildFly zip package, then gives the code to do that, great!   However,
right after those instructions, it gives you an option to use Galleon
instead with different code, so it's kinda confusing at first. There are a
few other places like this in the documentation as well, not the end of the
world but it shouldn't be looked at as a step by step instructional guide,
which is what I had assumed it was.  For me, it was such a hassle that I
found it necessary to create install scripts that not only included the
official commands to simplify and quicken installation but also to fill in
the missing information that was causing some failures.  Most of these
blanks were permissions and ownership issues that are usually assumed when
writing technical documentation but are absolutely needed in a script.
Again not a big deal, but it took lots of trial and error with many reverts
of snapshots.

Ultimately though, the main issue came down to using the recommended SQL DB
and connectors for installation, MariaDB.  I could never get MariaDB to
work with EJBCA.
The prime issue I had with the documentation was there was *nothing* on
using a SQL connector with the DB, this fact seemed to be assumed by the
documentation and escaped me as well.  Looking back I should have known as
well, one of my many positions was as a MS-SQL admin for a few years,
however, this project was my first one after a 4 year hiatus from IT.
Moving on, after that was realized, with the proper connector installed
*and* the new knowledge that I could just drop the connector into
/opt/wildfly/standalone/deployments and wildfly would import it (I was
trying to modify the standalone.xml file) MariaDB would still not work.  I
can't remember the exact error, but it was something to do with missing but
expected information from the connector itself.

With my new knowledge, I switched back to MySQL( I had originally used
MySQL but couldn't get anywhere due to Wildfly not recognizing it as I was
modifying the standalone.xml file manually then) and their connector.  I
continued having connection issues but was making progress and soon
realized that MySQL changed their connector schema and thus the connection
strings had to be changed in the database.properties file. The
database.driver field changed from: `
*#database.driver=com.mysql.jdbc.Driver*` to `
*database.driver=com.mysql.cj.jdbc.Driver*`. Once that was discovered it
was smooth sailing from there. For your reference here is the MySQL doc
that helped me discover the issue:
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-api-changes.html

Sorry about the long brief, but I wanted to be thorough.  So given all
that, let me provide you with a few questions to discuss amongst your
team.  Who is the audience of the documentation? Do you feel it's
adequately developed for anyone with IT experience of X years to use it to
fully install ejbca-ce with zero outside assistance? Is that even the goal?
What is the goal of the documentation? Most importantly, has anyone *not*
on your team or within the company who has an IT background gone through
this documentation like I did and actually tried to install ejbca-ce for QA
or Process Improvement?

I tried to send the scripts as well, but google doesn't like them for some
reason and I can't add your generic email to my dropbox, so if you want
them to look over, send me another email address.

Thank you for reaching out, I hope this has answered your question. Let me
know if I can clarify or assist in any other way regarding this matter,

Steve Osborn
Network and Systems Engineer, Lead
***@***.***
Diesec, Inc
https://diesec.com/

**Comment by primetomas** [comment]
Thanks for the thorough answer.

The SQL connector is the "Add Database Driver" here:
https://doc.primekey.com/ejbca/ejbca-installation/application-servers/wildfly-26#WildFly26-AddDatabaseDriver

I agree that the two options of using the zip of Galleon is confusing, especially if you are not experienced with Galleon (I'm not and just use the zip, but has done that a thousand times).

I'll create a ticket for the developers, so make the flow a bit easier to follow. There are also many optional parts, such as starting WildFly as a service, which you don't need if you just try it out.

Admittedly, installing from source is quite cumbersome, in some aspects unavoidable with the  amout of components involved (application server, database, etc), and the configuration differences you want to do if you just want to make an easy test compared to installing it securely and scalable for scalable production. 

Containers is definitely a much more easier option, both for testing and production actually.
https://hub.docker.com/r/keyfactor/ejbca-ce
(and of course there are the other packaged Enterprise solution like HW appliance, Cloud or SaaS)

I'll create some documentation ticket for the devs.

Cheers,
Tomas

**Comment by Synertry** [comment]
Hello, so as [uedvt359](https://github.com/uedvt359) mentioned, I would just have to drop the docs to the right location.
I still needed to edit the web.properties as [fliegerwolf](https://github.com/fliegerwolf) with `web.docbaseuri=internal` to actually show the [?].
The URLs do not seem to work though.

Does anyone know where the destination is supposed to be in the docker container?
I tried `/etc/ejbca/doc`, `/etc/ejbca/doc/dist`, `/opt/keyfactor/ejbca/dist`, `/opt/keyfactor/ejbca/doc` and ``/opt/keyfactor/ejbca/doc/dist` to no avail.

As the workdir is set to `/opt/keyfactor` I assume it has to been there somewhere. Here is shallow tree view of /opt/:
```
/opt/
|-- keyfactor
|   |-- appserver -> /opt/keyfactor/wildfly-26.1.2.Final
|   |-- bin
|   |   `-- internal
|   |-- configdump
|   |-- dbopt
|   |   |-- mariadb
|   |   |-- mssql
|   |   |-- oracle
|   |   `-- postgres
|   |-- ejbca
|   |   |-- bin
|   |   |-- conf
|   |   |-- dist
|   |   |   |-- assets
|   |   |   |-- attachments
|   |   |   |-- clientToolBox
|   |   |   |-- ejbca-ejb-cli
|   |   |   |-- ejbca.ear
|   |   |   |-- images
|   |   |   |-- js
|   |   |   |-- logtypes
|   |   |   |-- rest
|   |   |   `-- ws
|   |   |-- doc
|   |   |   |-- dist
|   |   |   `-- sql-scripts
|   |   `-- src
|   |-- secrets
|   |   `-- persistent -> /mnt/persistent/secrets
|   |-- tmp
|   |   `-- tmp.8VKttNZ6bv
|   `-- wildfly-26.1.2.Final
|       |-- bin
|       |   `-- client
|       |-- modules
|       |   `-- system
|       `-- standalone
|           |-- configuration
|           |-- data
|           |-- deployments
|           |-- lib
|           |-- log
|           `-- tmp
`-- primekey -> /opt/keyfactor
```

Or the URL-Rewriting needs to be tweaked. The documentation currently links to `https://$Domain/ejbca/doc/index.html`.

**Comment by Synertry** [comment]
Anyone looking to accomplish this for the container version.
With a proxy you can redirect the specific location to another path where the static docs should be served up.
Nginx location example:
```nginx
    location ~ ^/ejbca/doc/(.*)$ {
        root /var/www/$host/doc/dist;
        index index.html;
        try_files /$1 /$1/index.html /index.html;
    }
```
Make sure the directory and it's content exists:
```bash
mkdir /var/www/<dns-name-of-ejbca-instance>
```
and drop the complete doc dir from the zip to this location.
